#!/bin/sh

set -e

if dpkg --compare-versions "$2" lt-nl 2.3-24; then
	deb-systemd-helper purge anacron-resume.service >/dev/null
	deb-systemd-helper unmask anacron-resume.service >/dev/null
fi

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/anacron" ] ; then
	chmod +x "/etc/init.d/anacron" >/dev/null || true
fi
# End automatically added section

